version: "3.7"
name: "zloyegor-iot-task"
services:

  iot-db-source:
    image: mongo:latest
    container_name: iot-db-source
    networks:
      - iot-task-overlay
    command: >
      bash -c "
        (sleep 10 && mongosh --eval \"
            rsconf = {
              _id: 'myRS',
              members: [{ _id: 0, host: 'iot-db-source:27017', priority: 1.0 }]
            };
            rs.initiate(rsconf);
            rs.status();                                                             
          \") & mongod --replSet myRS --bind_ip_all
        "

  iot-db-target:
    image: mongo:latest
    container_name: iot-db-target
    networks:
      - iot-task-overlay
    command: >
      bash -c "
        (sleep 10 && mongosh --eval \"
            rsconf = {
              _id: 'myRS',
              members: [{ _id: 0, host: 'iot-db-target:27017', priority: 1.0 }]
            };
            rs.initiate(rsconf);
            rs.status();                                                             
          \") & mongod --replSet myRS --bind_ip_all
        "

  iot-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: iot-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - iot-task-overlay

  iot-kafka:
    image: confluentinc/cp-kafka:latest
    container_name: iot-kafka
    ports:
      - "9092:9092"
    depends_on:
      - iot-zookeeper
    networks:
      - iot-task-overlay
    environment:
      KAFKA_ZOOKEEPER_CONNECT: iot-zookeeper:32181
      KAFKA_LISTENERS: INTERNAL://iot-kafka:29092,EXTERNAL://iot-kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://iot-kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  iot-kafka-connect:
    container_name: iot-kafka-connect
    build:
      context: .
      dockerfile: connect-mongodb.Dockerfile
    depends_on:
      - iot-kafka
    networks:
      - iot-task-overlay
    environment:
      CONNECT_GROUP_ID: 1
      CONNECT_CONFIG_STORAGE_TOPIC: connect-mongodb-config
      CONNECT_OFFSET_STORAGE_TOPIC: connect-mongodb-offset
      CONNECT_STATUS_STORAGE_TOPIC: connect-mongodb-status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
      CONNECT_BOOTSTRAP_SERVERS: iot-kafka:29092
      CONNECT_ZOOKEEPER_CONNECT: iot-zookeeper:32181
      CONNECT_AUTO_CREATE_TOPICS_ENABLE: "true"
      CONNECT_REST_ADVERTISED_HOST_NAME: iot-kafka-connect
      CONNECT_REST_PORT: 8083

  iot-connector-setter:
    image: curlimages/curl:latest
    container_name: iot-connector-setter
    restart: no
    networks:
      - iot-task-overlay
    command: sleep infinity
    volumes:
      - ${PWD}/connector:/home/curl_user/

  iot-kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.0
    container_name: iot-kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - iot-kafka
      - iot-kafka-connect
    networks:
      - iot-task-overlay
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: iot-kafka:29092

networks:
  iot-task-overlay:
    driver: overlay
    attachable: true
